config/routes.rb
Neteyes::Application.routes.draw do
  match 'project' => 'project#index'

  resources :desks

  root :to => 'pages#welcome'

end

app/models/desk.rb
class Desk < ActiveRecord::Base
  attr_accessible :title, :options
  belongs_to :user
  serialize :options
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/desks_controller.rb
class DesksController < ApplicationController
  # GET /desks
  # GET /desks.json
  def index
    @desks = Desk.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @desks }
    end
  end

  # GET /desks/1
  # GET /desks/1.json
  def show
    @desk = Desk.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @desk }
    end
  end

  # GET /desks/new
  # GET /desks/new.json
  def new
    @desk = Desk.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @desk }
    end
  end

  # GET /desks/1/edit
  def edit
    @desk = Desk.find(params[:id])
  end

  # POST /desks
  # POST /desks.json
  def create
    @desk = Desk.new(params[:desk])

    respond_to do |format|
      if @desk.save
        format.html { redirect_to @desk, notice: 'Desk was successfully created.' }
        format.json { render json: @desk, status: :created, location: @desk }
      else
        format.html { render action: "new" }
        format.json { render json: @desk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /desks/1
  # PUT /desks/1.json
  def update
    @desk = Desk.find(params[:id])

    respond_to do |format|
      if @desk.update_attributes(params[:desk])
        format.html { redirect_to @desk, notice: 'Desk was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @desk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /desks/1
  # DELETE /desks/1.json
  def destroy
    @desk = Desk.find(params[:id])
    @desk.destroy

    respond_to do |format|
      format.html { redirect_to desks_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  helper 'joosy/sprockets'

  def index
    render nothing: true, layout: 'project'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/desks_helper.rb
module DesksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/desks/_form.html.haml
= form_for @desk do |f|
  -if @desk.errors.any?
    #error_explanation
      %h2= "#{pluralize(@desk.errors.count, "error")} prohibited this desk from being saved:"
      %ul
        - @desk.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :options
    = f.text_area :options
  .field
    = f.label :state
    = f.text_field :state
  .field
    = f.label :user
    = f.text_field :user
  .actions
    = f.submit 'Save'

app/views/desks/edit.html.haml
%h1 Editing desk

= render 'form'

= link_to 'Show', @desk
\|
= link_to 'Back', desks_path

app/views/desks/index.html.haml
%h1 Listing desks

%table
  %tr
    %th Title
    %th Options
    %th State
    %th User
    %th
    %th
    %th

  - @desks.each do |desk|
    %tr
      %td= desk.title
      %td= desk.options
      %td= desk.state
      %td= desk.user
      %td= link_to 'Show', desk
      %td= link_to 'Edit', edit_desk_path(desk)
      %td= link_to 'Destroy', desk, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Desk', new_desk_path

app/views/desks/new.html.haml
%h1 New desk

= render 'form'

= link_to 'Back', desks_path

app/views/desks/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @desk.title
%p
  %b Options:
  = @desk.options
%p
  %b State:
  = @desk.state
%p
  %b User:
  = @desk.user

= link_to 'Edit', edit_desk_path(@desk)
\|
= link_to 'Back', desks_path

app/views/layouts/application.html.haml
!!! 5
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7 ]
  = '<html class="ie6" lang="en">'
/[if IE 7 ]
  = '<html class="ie7" lang="en">'
/[if IE 8 ]
  = '<html class="ie8" lang="en">'
/[if (gte IE 9)|!(IE)]
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=7")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Untitled"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .container
      .navbar
        .navbar-inner
          %a(class="brand" href="/")
            Net Eyes
          %ul.nav.pull-right
            %li.active
              %a(href="/project/")
                Project
      .row
        .span6.offset3
          = yield

app/views/layouts/project.html.haml
!!! 5
%html
  %head
    %title> project

    :javascript
      window.joosy = {
        libraries: #{extract_sources_and_sizes_from_include_tag('project')}
      };

    = stylesheet_link_tag 'application'
    = csrf_meta_tags

  %body
    = javascript_include_tag 'project_preloader'
    #application
      #preloader
        Loading application...
        %span#percents 0%

app/views/pages/welcome.html.haml
%h1 Pages#welcome
%p Find me in app/views/pages/welcome.html.erb